sudo: required
language: ruby
services:
- docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=dairyd/debian
  - secure: E1DnVNbKpKzdTFJsYETXPrMDaTcW3ZaBUpIN0V3BpygClDjKix6Mamcabt8KAiy4xgZgfng0FoWKw7ACZzGTI7T0Do68Nm0BopcG+kbBUgAzSsX1Ayj3MiAVYpjWWTWZJLrHSoF1Gv44072Q/dpZmH0DXAMn76HcCDGr2pIP3TWtDY0Je5sDbV6D5xPFdFbL+Qw49GfiJpOrkjDxvcVnXfcetTbADDIN92SQAMEYCvAlvXJI4e2F5on2u/EUdwRW/TtfejC0W4apVn5lGl6txL7hDT6JzjBNiwdwHTuSGnHMKECsR6b/O6ICCDvRqmGuMByxxFvACEnvEKbbCteN0xoZLVGioxW+PyoyUWZsMQRF7Y+ekypNy8sgkjIYMbjmKsRCbo1JKAgFdglgvo4VTv66mfRmcdZu7q0dWcVamzPpkB6R8F1vN+aZNykxzHeFJ7cLn4ZaCZyYu/UDga0kOr6NgA0n//KWaI4Ex3YimlYrp+Dg7/AxH6AziCg+HHC0lMysyFLa6mFk2zSMwOPUzGd/q1QXia7NZa1wLuBjb4rWsdZVPQ3ekIlBSOESDGINu2jWQgKInWPeKV6b+hrZt64bw/UV0kImBJkV3TOZ+15oKHf3ze2VGhPiTLqhLycFca8YmvJ4A8iEYHqlKQ5VoeY5a8T+o11k23JgRul7g28=
  - secure: PsXKn2GbY5mZScsSynIvdh2QnhhjYyz9dDzkeLRcQOohH7yQ4CzE9e3GXrQRsxMCqiMD2PHlErYfZ6dq0FFFwdc9wk9aAcy0XRlGJoSyvGXdxU29bYAi6199LPcvB0hklTTFXvahLCZADEQMCE+9eLfFLcp/ejNJxCcScOP7d9CfqpXT8j5pOZJ2RMRJqiATDgZgpJNRKsjAWIXRV6s9Kep40rNmeGzBfvKDboAcVX7KiFjMM3e2XR4iL+CBqLozA8KT10vbCmcpCFQ3C++IRLdI9cY5k6WaTM1KIpMMsS7eZbhrDjS13KLEJbUUXnKOLwO/7JWs9cobQHtEp98Zo9NtU2Til8dC7tN0SAtXgFpI8AqY5x3OJrbsnAlru361V7xs/55Gk43ZKWLvGptE893aMCnR6KwdwZCIbzcQ39bCbXpllHa84VBke3biT2luvUBA3MWlsY3jiNltphhsBV32x4cz9HnWDbQWsHUlcSECndWmiMV5z+UU+EgoIQgRRCvgvYAn97DdnOtM0LO4ndXs5PcW4hMDlqkhJSQNKOTe57p+Pwv2IitZNfWzUQ2oJILq3yRMTq/hh6ZTE8WSIMB5qmeBw5uCn4UVcUk9Fg9vgB2Pd8Zx8kKS22bw5ZD5sGSE+kgxOTkbGZ+CaBrCdVhkWY18TGMFCKKlGUdLzEk=
script:
- export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master"
  ]]; then echo "stretch"; else echo $TRAVIS_BRANCH; fi`
- export REPO=dairyd/debian
- docker build -t $REPO:$TAG -f Dockerfile .
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
  docker tag $REPO:$TAG $REPO:$TAG-$(date -u "+%Y%m%d")-$TRAVIS_BUILD_NUMBER; docker
  push $REPO:$TAG-$(date -u "+%Y%m%d")-$TRAVIS_BUILD_NUMBER; fi
- docker push $REPO:$TAG
