sudo: required
language: ruby
services:
- docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=dairyd/debian
  - secure: k6b3/3Be3/J5UWgEoGf4CUdq0eEsYRqRS1z3egVQDp1xFSh6ycoCLxM+m6pJdp1pLpLN791eZ4XgF8mNs4NI8SyFkpHfYLUOY3vjdobtkkKyD4pHbGQqoe1D2xo3sTWlIiSm4N/Eo3p/hsUHmr5ocIXm/km2ZfGIGNJui9gDfsEoIowmNBGITtNSBw2MCznQIKUgcuO1OMJ5QLoTjLqYzalg/nbzmeVB8EaS2Ujk/uVr0huMMTl2Ab/JnJ+iBoEoAaeB967XmnTXpurOMR79wSwVay9VPGTHkMumnF1jBp1AhgCHS0ERi6Mt5v8IYjL2o7XY/usQu7bye2DoTIf2DGjchSY4Yr6HWtmDSnFJLOC4yUvgPdkeoutGNNrqsaH8I6iHC9Wj4eVJdm9L6etxBEotbbAWqN88EkxW1WwA/wTvKbiC4p2CnMmu+vBgko0ToxZtFPC817bBb8maGSp2yeUvdOnESW4qjCueVMgSvtce8EY3eEKE0ctHBg+oZl1SHtVotQa374LygurNSertqRK3plk0VzNZuXA2ldBxatjm/gR/efvEa8Rustslsp6P/1WLH6ep3SUdMogvblk26I78K0Ehbl/8x0b0PEOT8xqiDAp6XBZ7dZYBHAAJEi6mmerjSvFgWedyhpyJw3bfA+Xp9rJ0Q4GcGbCxLPXx+hA=
  - secure: pcjG8A58NMmTmyU2QieOb8+X4P0M6Fzj2mS6UJdlJWjZ69pFtVtQcozUbml87+QUiG3kDyaR67GhnIszA/3P+8z1DSfQdc3vUXnwd1F0jiKEyXg/RToTSQQ5lWanGc6wAYro+w2sY1ngt5rbEq1MUfySR2DAYoNvo+9eQ/BrG1BNQz1jlIQ3g97F2m2Nc0nnmqu4mKHYC3U6TBAbok8tl9XfdZ2Aem5NlbN97xEdi2IFRUO1Fn0U4A8N0yQXveYpAVyHYp2OS6pyy0jsBzpYPIUJhDaLJNGdtw9+fOvtAr2Hvjd20gey1M+PTr9RKEiCnbvAsPEhGQpE1n6eOOXh/FPm0R/00whdZx77IkERMZ3ONPIx8DGzkfaF6ULY2grKrPGW8aQwMox7hViVLLfQCZyxtvyCDypeI+J/ktQzbM+uQL+983RvuT/nfRNzLfoo1TgCIDYE7lZ6N5tDgefS6yCC0A9TmIz8Zv6xm/F+yL+857+EXP2zf+iQrOkcj1k2sOwzobmuPwJyXhGLoziZGOb/93/jrRRjGg3/n/qSjQ3KgEG0PUHCqoZQZadMP637vztFWewEzcOF5dvIEKyAShofm1FZP38mkwwCr8Bmc54rWKVIUZ/esLtROMcwc0PwKBbdqFt+rh9UHuxb+/qZwoX8Ip5GWB+TG8wGfHcBBlA=
script:
- export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master"
  ]]; then echo "buster"; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi`
- export REPO=dairyd/debian
- docker build -t $REPO:$TAG -f Dockerfile .
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
  docker tag $REPO:$TAG $REPO:$TAG-$(date -u "+%Y%m%d")-$TRAVIS_BUILD_NUMBER; docker
  push $REPO:$TAG-$(date -u "+%Y%m%d")-$TRAVIS_BUILD_NUMBER; fi
- docker push $REPO:$TAG
