sudo: required
language: ruby
services:
- docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=dairyd/debian
  - secure: OdCVSAfDNS0ccTQmQdk/1i09K9eGUbPIS+Tq0pNIz4rz7VUFEEKmtG79QbOoBEM4+fszZw8+c/Hav4PATwxzTuyJC0Dlk6nPu/EScuOAwFdCp+vzjuy+HnRrOkv1vt/g5yfPLzMTyF/GqKKuzqfDj2Qwym6+m4JksrbggECeOO6ett6gaNch11mMzj/YkXxMgQy2kN9cmB+sDjakc2I/kNNSlXH20epX+sPWLiMUwl/G/xGiRLvcTMfhbHOWziG8GvYwi89VigcHvHckfTvHii5E5MhnYitDjlCpCu15D9ffjrkPiTqqRSD/sZ0GDeD9WGW2B36Po/xdYBHzGptGUFI+I/newKSVd/XiBVtdSgnTd2sMyubU0y9cnUpDXdnJ6Con2mClaarJHI5oMtZVXpmcBKVa7jhIWB/d/dqGXJonh3eEJIYuuZSALFDpqJEY3SomS0Zqp804aa2OZahPP0mxkBj36e92P/SmoM8K5veTjlzkWHYUi62DvGo054TDs45NU17DpvoJPBKbnVvtR4cYnyu+AU6TucRWwtt+XLKskWYYsomsK9n/0s4yHbYjf79Mog7jbvCiJXL/PpKFhg7JpxGBlft9CfJZ28MlAoTFCgHJj+dIjY3z/vc3vwY4UBBs7PC8YQN+y07legfxltYdqCNpisUrDTLo6sw/Gus=
  - secure: MMBQ8OHnH1E//RHc/HJAexvrVVj+Jhk/qjOnrKkNL3QDotv5ARHPtwpdOjwufuNbhkeyqlBLh9lmrVaFkSeKppAzPWOETbNZJx9lTfITZ2+cRzrU84sEAemI63jbUX9ulnqrE67l9uvwaQtCWdGFBQkaAP9S4UCpOE8/GYKfgcmBW7J7cIqPIIRBR6oPdxXmze6BI3ZB5noMFO69pqIQMendRU+XY40lgTg+s8fqNaA4aQon3e2YHTDh4X4TL09cpIRP5CtfmHSggGqvntfb0yv6QTD6pYUkdyAj1BZpCQxyuOw+n/tIxcV1skP5BtqlUbcRDzNH05JckXj3r5o/6uH6Pvz63/P7sQLjegdRy25q1tK+Vhb7skKOaPoign0SSy0UstBMW/XOXGXrreMCgXSoPxQvnHw4tRP66dnDjhj0jam9u2zqlNpDbVmwhDpwh0r4MCYsSY1HcAZZt7UYMzr/5/ezCsY9PiCGnyC2OcyN9sDqs5O0UuSLyGz3Z1TFWMmdJRNfUwsfO8eHmZQQQzGv8NciNQ7LPPZ1021O1S/7I3Slhsp8UhRd/gTATKmryHgkQltTLzvNA+Mr7n4wjYsrqr4vuR0niHoVT8WOe/N28RCpVjjUaZhxLuMie9USqr2DdGsyp9itT4h6wFbD71bj0zU3/jK3Yuani6b3f/Y=
script:
- export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master"
  ]]; then echo "stretch"; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi`
- export REPO=dairyd/debian
- docker build -t $REPO:$TAG -f Dockerfile .
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
  docker tag $REPO:$TAG $REPO:$TAG-$(date -u "+%Y%m%d")-$TRAVIS_BUILD_NUMBER; docker
  push $REPO:$TAG-$(date -u "+%Y%m%d")-$TRAVIS_BUILD_NUMBER; fi
- docker push $REPO:$TAG
