sudo: required
language: ruby
services:
- docker

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=dairyd/debian
  - secure: SDufSPN1yzrMjuaXenPWoslxdrQqxE4G5J3p1e4ppAOzzS937o3rfP4tbZe10VZLYmW8t4n13anV6iMkCTGrzbMsngq0PEniykJbVw6XJeti531HjdYUinTft7M49fKdJ65q7R3QuYcn9brZP9rCH6FyNsez+REFLd4uGBqF3T/ERVYH+lPdjCTOhQ2dB5krcJogTbFMsD6HPPcfXwmn8wLiWdE63y9A4K57KTjx1mb9Hq3l/oYyOn7aGELk7gQ4NDBAkkfFXmCiH9GXgPAXkzm6o5fKDpW+dmQik88SGTNriGUfFuA1Kvffy6neRAOcCSCnF97CTADclpeQTQkuPkFTgr+2atInuSWL+zRumBJcHC90CBUdlZNVCbiqTmbkBlLgWOLUq+gR3uJ3J68sRxsJ8upc83Ik2GviTiXeOC2CK2s+yE1BKydPskOw6dU+UyIgbfczvepQTeSNpys1NOhQ1O+7+jJZDJFEXrrR3eD1b/jSp57JcPUk3aCc4bb+wd7a/VY0owB99+ooxl9xvWWkp/hA9jc6hwclLYJ8jGQIbbb35IliKRTOoP05ro2RX0ETaALF5uVKJwirlA/IzWE9Ph/+OPgok/UJCclhs4h+MfzzzyaTGCjULjfEFCSoeg8D0WMFkG2nn1yWQhpZwvZgcpEoe2H9PJ9532lqhRM=
  - secure: OLjnePzI2Yp4foellf5OJ+Y39cafndaLYuZ9wTmfAXuad/O86qarUqsp4oLY1XNPQvD3wmlS6gLFIiXSWgARYs90rUiJigFBecxJ8IFWeKE+POaA5+ElQdhNhp34bd8ud4fobcrstYrdkxDpaOKaL3msPvecfOxer5oLKsEA5m2Y69dbRGHdP/iXf6VnVeBZ9IbDa58iF2aC4UBdfDgyWIVdgqS1vo1ftgaRw0c5yR1GYyqF9DS61Psu7fDscwJYHIB/EbTOVnJXcEKtDXUYO+xHwK9ItUv8mmbqgVU0TnEPiqmAcG05on3SyrK7fmTm8Zd7ipXlvTMtG078HHTvh/Wx9WLnQOWSYN47riVzgHsLn46/zWi0VwqrRAoJ+0N687frd5mssIzRCc1aIjv3htkDloNWAOHMfKEbIxIGDVLU8RjJSgOAGokH42BtAVVyUUcFSQAG3Wy/aCFyC1FrN7zPqJgzhuh9byZO9fF4wcBvMO++uwZ9rcImcyHtc0CeXXnODxirgX2WN2z149S74w50Ed8PNg4TfHFB6YHDd0SC8Vv+zhVIv0CLhZ8izE2VwsLn86/8gSQ4GCj9+BilybyhjsEor/iRk/PUJWah+Y5n9vCd8XCzYvvybcw5i70EUo2VnCYaTz6+sqwz4+BxdhrD9hdaJJmXwFSD0HEnlcY=

script:
- export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master"
  ]]; then echo "stretch"; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi`
- export REPO=dairyd/debian
- docker build -t $REPO:$TAG -f Dockerfile .

after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
  docker tag $REPO:$TAG $REPO:$TAG-$(date -u "+%Y%m%d")-$TRAVIS_BUILD_NUMBER; docker
  push $REPO:$TAG-$(date -u "+%Y%m%d")-$TRAVIS_BUILD_NUMBER; fi
- docker push $REPO:$TAG
